### ISSUE TITLE
Add Open source

### ISSUE THREAD

**Issue by fire17** [MULTI-ON/api#55]
Hi there,
Heard good things about your tech and approach
Just wanted to come and say I hope you'll consider developing MultiON AI openly

Soon there will be a plethora of ai projects like hyperwrite and yourselves and I can't wait to contribute to the ones that open

And in general I think most revenue will come from B2B/B2C business operations, open source would give you a super dev boost 

All the best!

**Comment by Div99** [comment]
Hi @fire17 we are considering more of our tech open-source starting with the API in the future. Please feel free to contribute and any suggestions, and look forward to more stuff coming soon
