### ISSUE TITLE
Unable to run event rsvp langchain example

### ISSUE THREAD

**Issue by tt-crazydiv** [MULTI-ON/api#62]
Hi,

I'm unable to execute example given here: https://docs.multion.ai/EXAMPLES/event_rsvps_using_langchain with latest langchain version. 

I've tried running it with AgentExecutor but couldn't get it to work. Also tried to downgrade langchain to version `<0.1.0` and tried a couple of 0.0.2xx and 0.0.3xx versions but couldn't find a version which runs this example like this.

Could anyone please tell which is the pinned langchain version to use which has stable multion support?

**Comment by Div99** [comment]
hi @tt-crazydiv langchain changed their sdk recently, please directly use the MultiOn API directly without langchain.

We are also working with langchain folks to migrate MultiOn Agent support to their newer sdks
