### ISSUE TITLE
browse returns sessionId but create_session returns session_id

### ISSUE THREAD

**Issue by HowieG** [MULTI-ON/api#63]
sessionId/session_id in response are inconsistent. Noticed when running the Multion_api_example.ipynb which failed when setting session = response["session_id"] after running browse

browse:
```
{
  'result': 'ANSWER: The weather today in San Francisco is mostly cloudy with a temperature of 57°F (13°C). The precipitation is 0%, humidity is at 90%, and the wind speed is 5 mph.\n\nSTATUS: DONE',
   'status': 'DONE',
   'lastUrl': 'https://www.google.com/search?q=weather+today+in+san+francisco',
   'content': '',
   'screenshot': '',
   'sessionId': '0c8dcab0-9a9b-46fc-96b4-02544d5c8d6e'
}
```

create_session:
```
{
  ...
  'session_id': ...
}
```

I can get a real sample result for create_session in a bit, having trouble connecting at the moment

**Comment by Div99** [comment]
thanks for letting us know.

Cc. @NamanGarg20 to take a look on this

**Comment by Div99** [comment]
Closing this as should be fixed now (cc. @HowieG )
