### ISSUE TITLE
get_screenshot() throws exception for empty string

### ISSUE THREAD

**Issue by HowieG** [MULTI-ON/api#64]
response:
```
{
  ...
  screenshot = ''
}
```

```
screenshot = response["screenshot"]
get_screenshot(screenshot)
```

When running Multion_api_example.ipynb with set_remote(True), browse() comes back with an empty screenshot - which might also be a bug, it works fine when set_remote(False). This empty screenshot causes get_screenshot() to throw an exception. May want to handle it elegantly so that the notebook continues.

**Comment by Div99** [comment]
tagging @NamanGarg20 to take a look at this

**Comment by HowieG** [comment]
Hey Div, still broken. I don't see a commit for this in main btw maybe fix wasn't merged
<img width="1255" alt="Screenshot 2024-02-25 at 4 03 03 PM" src="https://github.com/MULTI-ON/api/assets/15098079/ba419afe-7d88-40ff-8816-45867cbcd89b">

**Comment by bgeils** [comment]
hitting this error as well with `multion==0.3.16`

**Comment by hepengfe** [comment]
I am having similar issue. When I set `response = multion.set_remote(False)`, running `multion.get_screenshot(response, height=800)` will raise 
```
Traceback (most recent call last):
  File "start.py", line 28, in <module>
    multion.get_screenshot(response, height=800)
  File "/Users/xxx/miniconda3/envs/multion/lib/python3.8/site-packages/multion/multion.py", line 699, in get_screenshot
    return _multion_instance.get_screenshot(response, height, width)
  File "/Users/xxx/miniconda3/envs/multion/lib/python3.8/site-packages/multion/multion.py", line 450, in get_screenshot
    img = Image.open(img_io)
  File "/Users/xxx/miniconda3/envs/multion/lib/python3.8/site-packages/PIL/Image.py", line 3339, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x100af33b0>
```

Upon checking the screenshot link on amazon aws, it seems to be corrupted.
