### ISSUE TITLE
API Key Description text not visible in Dark mode

### ISSUE THREAD

**Issue by HowieG** [MULTI-ON/api#67]
https://jam.dev/c/876f3180-47a7-4a8d-afaf-667322b3d7ad

**Comment by weeebr** [comment]
<img width="836" alt="Bildschirmfoto 2024-02-26 um 18 59 00" src="https://github.com/MULTI-ON/api/assets/1096639/91c0bf3c-af9e-4731-a852-47137c59f8f6">
same thing here with this input field.
